apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      version: blue
  template:
    metadata:
      labels:
        version: blue
        app: messaging-app
    spec:
      containers:
      - name: messaging-blue
        image: yourdockerhubusername/messaging_app:2.0
        ports:
        - containerPort: 8000
